# Generated by Django 6.0 on 2026-01-09 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base', models.CharField(max_length=100)),
                ('principal', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to='media/team_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('number', models.IntegerField(unique=True)),
                ('country', models.CharField(max_length=100)),
                ('flag', models.ImageField(blank=True, upload_to='media/flags/')),
                ('image', models.ImageField(blank=True, upload_to='media/driver_images/')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.team')),
            ],
        ),
    ]
